non-aloc-concurent version
fyne-io/life pull request #3
Opened 2021-09-07 08:58 UTC by MatejMagat305

2021-09-07 12:11 UTC, andydotxyz commented
Please provide some more information, this bug/feature request does not make sense.

2021-09-07 12:16 UTC, MatejMagat305 commented
improvements #1

2021-09-22 12:52 UTC, andydotxyz requested changes
A question about the wait model, and some notes about un-needed changes that should be backed out.

2021-09-22 12:52 UTC, andydotxyz commented on AUTHORS
> +Andy Williams <andy@andy.xyz>
Files should have newlines at the end - I don't think this change is needed

2021-09-22 12:52 UTC, andydotxyz commented on LICENSE
> +
Please don't edit our license file

2021-09-22 12:52 UTC, andydotxyz commented on board.go
> +	nextGenCells         [][]bool
This formatting looks off, please run `goimports -w .` to correct.

2021-09-22 12:52 UTC, andydotxyz commented on board.go
> +				b.ch<-true
I think this is local to the method, so does it need to be in the game state?
Also I wonder, does it not fit the `WorkGroup` model better?

2022-05-20 12:18 UTC, Jacalz commented
I did some benchmarking on this and it seems that the concurrent version is slower than the version before. It seems like the pre-allocated board does improve quite a bit though. @MatejMagat305 Would you be fine with me opening a PR for that? If not, feel free to update this PR.

2022-05-20 22:01 UTC, MatejMagat305 commented
yes, sorry, the only impovement is not aloc ...

2022-05-20 22:01 UTC, closed without merging